import { Geist, Geist_Mono, Abril_Fatface } from "next/font/google";
import "../globals.css";
import { TopbarMenu } from "@/components/ui/topbarMenu";
import { TooltipProvider } from "@/components/ui/tooltip"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <TooltipProvider>
          <TopbarMenu/>
          {children}
        </TooltipProvider>
      </body>
    </html>
  );
}

